---
title: "02_analysis-simple"
author: "Eduardo Zanette"
date: "2022-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library("here")
library("nlrx")
library("dplyr")
library("readr")
library("ggplot2")
library("ggspatial")
library("sf")

# GIS
our_crs <- "+proj=utm +zone=22 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
gua_xlim_all = c(780000, 782350)
gua_ylim_all = c(7407080, 7408250)
gua.x.min = 781587
gua.x.max = 782361.5
gua_xlim_set = c(781050, 782350)   # c(781200, 782350) # closer
gua_ylim_set = c(7407050, 7408250) # c(7407250, 7408250)  # closer
sma_xlim_set = c(364400, 366000)
sma_ylim_set = c(7540500, 7541700)
taq_xlim_set = c(370500, 373200)
taq_ylim_set = c(7498750, 7500550)
suz_xlim_set = c(705300, 706200)
suz_ylim_set = c(7480800, 7481600) # 7480990,


# Plots
theme_set(theme_bw(base_size = 15))

simulated_shapes <- c("foraging" = 1,
                      "frugivory" = 19, 
                      "resting" = 1, 
                      "sleeping" = 17, 
                      "travel" = 1)

simulated_colors <- c("foraging" = "magenta",
                      "frugivory" = "#1E8449", 
                      "resting" = "grey", 
                      "sleeping" = "#E74C3C", 
                      "travel" = "grey")

# sf objects
load(here("Data", "06_sf-plots.RData"))

```

### Read empirical tree files
```{r}
treepath <- here("Data", "Movement", "Resource-trees")
trees <- read.csv(paste0(treepath, "/", "Siminputrow_trees.csv"),
                           sep = ",", dec = ".", stringsAsFactors = TRUE) #%>% 
  # mutate(group = recode(group, "Guarei" = "Guareí")) # to match all other datasets

feed_trees_gua <- trees %>% dplyr::filter()
sleep_trees_gua <- 

```

### Plot some examples
```{r}
ggplot(db) +
  geom_point(data = subset(db, breed == "seeds"), 
             aes(x = x_UTM, y = y_UTM, color = species, shape = `disp-day`)) + #https://stackoverflow.com/questions/60817705/filtering-values-in-ggplot2
  geom_point(data = feeding_trees_gua,
             aes(x = x_UTM, y = y_UTM, color = species, shape = `disp-day`)) +
  geom_point(data = sleeping_trees_gua,
             aes(x = x_UTM, y = y_UTM, color = species, shape = `disp-day`))

ggplot(subset(db, study_area == "Taquara" | `feeding-trees-scenario` == "Jan" | `random-seed` == 	2106024157)) +
  geom_point(data = subset(db, breed == "seeds"), 
             aes(x = x_UTM, y = y_UTM, color = species, shape = `disp-day`)) #+ #https://stackoverflow.com/questions/60817705/filtering-values-in-ggplot2
 
```

