---
title: "02_analysis-simple"
author: "Eduardo Zanette"
date: "2022-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library("here")
library("nlrx")
library("dplyr")
library("readr")
library("ggplot2")
library("ggspatial")
library("sf")

path <- here("Model_analysis", "Sensitivity-analysis",
             "v1.1_November2022", "temp")

# GIS
our_crs <- "+proj=utm +zone=22 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
gua_xlim_all = c(780000, 782350)
gua_ylim_all = c(7407080, 7408250)
gua.x.min = 781587
gua.x.max = 782361.5
gua_xlim_set = c(781050, 782350)   # c(781200, 782350) # closer
gua_ylim_set = c(7407050, 7408250) # c(7407250, 7408250)  # closer
sma_xlim_set = c(364400, 366000)
sma_ylim_set = c(7540500, 7541700)
taq_xlim_set = c(370500, 373200)
taq_ylim_set = c(7498750, 7500550)
suz_xlim_set = c(705300, 706200)
suz_ylim_set = c(7480800, 7481600) # 7480990,


# Plots
theme_set(theme_bw(base_size = 35))

simulated_shapes <- c("foraging" = 1,
                      "frugivory" = 19, 
                      "resting" = 1, 
                      "sleeping" = 17, 
                      "travel" = 1)

simulated_colors <- c("foraging" = "magenta",
                      "frugivory" = "#1E8449", 
                      "resting" = "grey", 
                      "sleeping" = "#E74C3C", 
                      "travel" = "grey")

# sf objects
load(here("Data", "06_sf-plots.RData"))

```

### Read empirical tree files
```{r}
treepath <- here("Data", "Movement", "Resource-trees")
trees <- read.csv(paste0(treepath, "/", "Siminputrow_trees.csv"),
                           sep = ",", dec = ".", stringsAsFactors = TRUE) #%>% 
  # mutate(group = recode(group, "Guarei" = "Guareí")) # to match all other datasets


# feed_trees_gua <- trees %>% dplyr::filter()
# sleep_trees_gua <- 

```


### Read simoutput (simulation) data
```{r}
db <- read_csv(paste0(path, "/", "02_Simoutput-simple.csv")) %>% 
  mutate(species = case_when(species == "[Celtisiguanaea]" ~ "Celtis iguanaea",
                             species == "[Eugeniasp.]" ~ "Eugenia sp.",
                             species == "[Syagrusromanzoffiana]" ~ "Syagrus romanzoffiana",
                             species == "[Pereskiaaculeata]" ~ "Pereskia aculeata",
                             TRUE ~ species)) %>% 
  mutate(
    SDD = SDD * 10  # SDD is in patches and 1 patch = 10 m
    ) %>% 
  droplevels()
```


### Plot some examples
```{r}
# theme_update(legend.key.size = unit(2, 'cm'))

# 1) Guareí
rseed <- db$`random-seed`[1]
group <- "Guareí"
breed <- "seeds"


db_filt <- db %>%
  dplyr::filter(
    study_area == group &
    breed == breed &
    `random-seed` == rseed
  )

# gua.p1  
gua.p1 <- gua.sf +
  geom_point(data = db_filt, aes(x = x_UTM, y = y_UTM, color = species, 
                                 # size = SDD,
                                 # shape = `disp-day`
                                 ),
             alpha = 0.4) +
  # scale_shape_manual(values = c(16, 17)) +
  ggtitle("Simulated seed dispersal coordinates")

gua.p1

# gua.p2
trees.gua <- trees %>% 
  dplyr::filter(
    group == "Guareí" & id_month == "Aug"
  )

gua.p2 <- gua.p1 +
  geom_point(data = trees.gua,
             aes(x = x, y = y, color = species, size = 5)) +
    scale_shape_manual(values = c(16, 17))
gua.p2

  geom_point(data = sleeping_trees_gua,
             aes(x = x_UTM, y = y_UTM, color = species))

```

