---
title: Summary of the meeting
# subtitle: If necessary
author: |
     | Ronald Bialozyt
# Northwest German Research Institute
abstract: |
  We planed to discuss the next point of Eduardo's project. We started 
  by discussing the paper of Ranc et al. 2022 "Memory drives the 
  formation of animal home ranges: Evidence from a reintroduction". 
  The question is about what to implement next and if this bi-component
  memory would be something to use in our model. The idea, that the
  attraction of the home range would suffice to create a sensible 
  home range seemed to be interesting.
#  \clearpage
  
bibliography: Eduardo.bib
csl: frontiers-in-sociology.csl# sets the style of your bibliography

date: "04. March 2022"

output:
  bookdown::pdf_document2: default
  word_document: 
    reference_docx: Lecture_template.docx
fontsize: 12pt
baselinestretch: 1.12
linestretch: 1.22
toc: yes
toc_depth: 3
lof: True
lot: True
fig_caption: yes
papersize: a4
tables: true
number_sections: yes
always_allow_html: yes
# These are LaTex settings to take care of floating figures/tables, line spacing, etc
header-includes:
#  - \usepackage{endfloat}
#  - \usepackage{setspace}\onehalfspacing
  - \usepackage{marginnote}
  - \renewcommand*{\marginfont}{\footnotesize}
  - \newcommand{\mn}{\marginnote}
  - \geometry{top=2cm, bottom=2cm, outer=5cm, inner=2.5cm, heightrounded, marginparwidth=3.5cm, marginparsep=0.5cm}
  - \usepackage[svgnames]{xcolor}
  - \usepackage{hyperref}
  - \hypersetup{colorlinks = true, linkcolor = DarkBlue, urlcolor = blue, citecolor = blue}
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \newcommand{\leftfootline}{}
  - \newcommand{\rightfootline}{\thepage}
  - \pagenumbering{gobble}
  - \pagestyle{fancy}
  - \fancyhfoffset[R]{3.2cm} % Kopf-/Fußzeile rechts überstehen lassen
  - \fancyhead[L]{\nouppercase\rightmark} % Firmenlogo
  - \fancyhead[R]{\nouppercase\leftmark} 
  - \cfoot{\thepage\ of \pageref{LastPage}}
  - \setlength{\headheight}{14pt}
editor_options: 
  markdown: 
    wrap: 72
---
\pagebreak
\pagenumbering{arabic}

```{r Setup..., message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'htbp') # Places figures 
knitr::opts_chunk$set(out.width = '100%', dpi=300)

# I usually load my libraries up front to keep things organized
library(bookdown)
library(knitr)
library(kableExtra)
library(ggplot2)
library(ggthemes)
library(ggExtra)
library(dplyr)
library(stringr)

library(flextable)
opts_chunk$set(echo=FALSE,
               message=FALSE,
               results = "asis") 
## usepackage_latex("booktabs")
## library(xtable)
## kable_styling(full_width = F)
```
 
&nbsp;  <!-- \pagebreak -->

[comment]: # (This actually is the most platform independent comment)

# Starting idea

The paper we liked to discuss was the one from
@rancMemoryDrivesFormation2022. In this paper the importance of
bi-component memory usage for home range generation has been
emphasised.

Our initial model dealed with something similar. The tamarins know
all of their feeding trees with their home range, this makes it to the
so called "spatial memory". The second component it called "working
memory" and was implemented in this way, that the tamarins do remember
on a certain amount of tree they visited last. The first component
defines attraction to the trees and the second component defines
repulsive to these trees.

So far I could not make out how they [@rancMemoryDrivesFormation2022]
actually select from the step length and turning angle distribution
the next location. \mn{Still to find out!}

# New modelling exercises

## Optimise Mayara's model using a GA

for the given parameter and variables

* two thresholds for energy budget
* time in tree before change
* action-time
* input_forget
* 50:50 chance of foraging or marking \mn{Maybe take marking out}
* change the "choice"  in "random-action"
	
Using a genetic algorithm and the nlrx-package.
   
## Implement a better "working memory"

In the current model, the working memory just remembers on the last
two trees visited (parameter: input_forget). This is definitely to
short. The removals of an tree within this memory depends only on the
next visit of a tree and has no time component.

## Using a stable "spatial memory"

We will not change the knowledge of the tamarins about the feeding
trees in their home range. This would become necessary only in the
case that we would like to simulate changes in the home range location
and size.

## Attractiveness of trees and sites

In the paper by @rancMemoryDrivesFormation2022 they used some value
for the attraction of the animals to certain cites. The parameters
defining this attraction are almost all landscape parameter. There is
also the time they spend in this site used to increase the attraction
to this site.

We could define some sort of attractiveness be the trunc diameter
of the trees. Later on we could think about different attractiveness
according to the feeding tree species.

* We will probably need some sort of attraction for each of the
  activities of the tamarins like foraging and marking. \mn{Not sure
  yet.}

# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent
